service: api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  environment:
    GOOGLE_EMAIL: ${env:GOOGLE_EMAIL}
    GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
    SHEET_ID: ${env:SHEET_ID}

functions:
  api:
    handler: src/ingest_reimbursement/index.handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
